name: Linux.

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  linux:
    name: Rocky Linux 8
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Install Docker
        run: |
          sudo apt install docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: First set up.
        run: |
          echo ${{ secrets.PASS }} | docker login --username ghazzor --password-stdin
          docker pull ghcr.io/telegramdesktop/tdesktop/centos_env
          docker tag ghcr.io/telegramdesktop/tdesktop/centos_env tdesktop:centos_env

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: clone
        run: |
          git clone https://github.com/kukuruzka165/materialgram --recursive -b main tdesktop && cd tdesktop
          export TAG=$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1)
          git checkout $TAG

      - name: materialgram build.
        run: |
          cd tdesktop
          docker run --rm \
          -v $PWD:/usr/src/tdesktop \
          -e CONFIG=Release \ 
          tdesktop:centos_env \
          /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
          -D CMAKE_EXE_LINKER_FLAGS="-s" \
          -D TDESKTOP_API_ID=27089606 \
          -D TDESKTOP_API_HASH=d14ed11b1ec58dfe89233e976834ea73 \
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=True \
          -D -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
          
      - name: Check.
        run: |
          [ ! -e "tdesktop/out/Release/materialgram" ] && \
          echo "BUILD FAILED" && \
          exit 1

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: mat
          path: tdesktop/out/Release/materialgram
          compression-level: 1
